export enum ActionType {
 REGISTER_REQUEST = 'REGISTER_REQUEST',
 REGISTER_SUCCESS = 'REGISTER_SUCCESS',
 REGISTER_FAILURE = 'REGISTER_FAILURE',
 LOGIN_REQUEST = 'LOGIN_REQUEST',
 LOGIN_SUCCESS = 'LOGIN_SUCCESS',
 LOGIN_FAILURE = 'LOGIN_FAILURE',
 LOGOUT_ACTION = 'LOGOUT_ACTION'
}
